spring:
  application:
    name: marketplace
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marketplace}
    username: ${SPRING_DATASOURCE_USERNAME:marketplace}
    password: ${SPRING_DATASOURCE_PASSWORD:marketplace}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update